// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVBqkfncHkd_1nfjXy55Op0K2XyukwtP0',
    appId: '1:39921959963:web:19b22fa0680c76e631a4be',
    messagingSenderId: '39921959963',
    projectId: 'tofu-f1re41',
    authDomain: 'tofu-f1re41.firebaseapp.com',
    storageBucket: 'tofu-f1re41.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcRGszGwTppBOpiEF_dqRsOMIe0cmRkYk',
    appId: '1:39921959963:android:150c0d57cec07d8931a4be',
    messagingSenderId: '39921959963',
    projectId: 'tofu-f1re41',
    storageBucket: 'tofu-f1re41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVw5dPZL1UswQPFYTigKHYed98RKsbAic',
    appId: '1:39921959963:ios:6345f8352957cc0731a4be',
    messagingSenderId: '39921959963',
    projectId: 'tofu-f1re41',
    storageBucket: 'tofu-f1re41.appspot.com',
    iosBundleId: 'com.dzakyadlh.tofu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVw5dPZL1UswQPFYTigKHYed98RKsbAic',
    appId: '1:39921959963:ios:6345f8352957cc0731a4be',
    messagingSenderId: '39921959963',
    projectId: 'tofu-f1re41',
    storageBucket: 'tofu-f1re41.appspot.com',
    iosBundleId: 'com.dzakyadlh.tofu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVBqkfncHkd_1nfjXy55Op0K2XyukwtP0',
    appId: '1:39921959963:web:a54eb243250fde1f31a4be',
    messagingSenderId: '39921959963',
    projectId: 'tofu-f1re41',
    authDomain: 'tofu-f1re41.firebaseapp.com',
    storageBucket: 'tofu-f1re41.appspot.com',
  );
}
